### ISSUE TITLE
"end of the stream or a document separator" error

### ISSUE THREAD

**Issue by unleashy** [wwilsman/js-yaml-loader#14]
Hi, I tried to use this library for the first time and immediately hit a _very_ cryptic error:

```js
ERROR in ./src/test.yaml (./node_modules/js-yaml-loader!./src/test.yaml)
Module Error (from ./node_modules/js-yaml-loader/index.js):
end of the stream or a document separator is expected at line 2, column 43:
     ... orts = doc.length <= 1 ? doc[0] : doc;
                                         ^
 @ ./src/index.js 1:0-46 3:12-16
```

Then webpack quits because js-yaml-loader didn't export a Buffer or String (yeah, since it failed.)

I've made a (hopefully) minimal test case and put it on this repo: https://github.com/unleashy/js-yaml-error-demo

As you can see in [src/test.yaml](https://github.com/unleashy/js-yaml-error-demo/blob/master/src/test.yaml), the file is empty. It doesn't seem to matter what you put in the yaml file, so I'm guessing it's some issue in the library itself; weirdly, "end of the stream or a document separator is expected" is a JS-YAML error message, so it's like JS-YAML is trying to parse the JS code... somehow? I don't know.

In any case, thanks!

**Comment by wwilsman** [comment]
Hey @unleashy! Thanks for opening an issue!

> it's like JS-YAML is trying to parse the JS code

This is exactly what's happening. You're actually using the loader twice, once in the webpack configuration and once inline with the import statement.

Webpack only supports using one of these options. There's also a link in the readme to webpack's documentation where it specifies this: https://webpack.js.org/concepts/loaders/#using-loaders. 

Although I could see how you might make that mistake based on the readme alone. I'll update it to specify using one or the other, but not both.

**Comment by wwilsman** [comment]
@unleashy could you check out the [new readme](https://github.com/wwilsman/js-yaml-loader/blob/d0c8c8dc611fdad1e8c51d66f5ba5d289f215818/README.md) from #15 and let me know if this would help clarify to anybody else in the future?

**Comment by unleashy** [comment]
Ohhhhh!!! Wow I feel so stupid lol. I'm new to JavaScript and that didn't occur to me at all.

The new readme helps, but I think you can put an "Or" before the "using the loader via Webpack configuration" so that it's extra clear.

In any case thank you v much :heart:

**Comment by wwilsman** [comment]
No problem! Glad to help ❤️ 

[Added the "or"](https://github.com/wwilsman/js-yaml-loader/blob/f2f6edcfc6c1350ca1f962a0b578a6ea74c12ce2/README.md); merge and release incoming!
