### ISSUE TITLE
"Cannot find module" with NextJS and Typescript

### ISSUE THREAD

**Issue by luisfelipesdn12** [wwilsman/js-yaml-loader#19]
# What is happening

Hey there! First of all, thank you for this great module!
Basically, everything works fine when I run `yarn dev`, but when I try to build the project with `yarn build`, the following error came:

```cmd
yarn run v1.22.5
warning ..\..\..\package.json: No license field
$ next build
Failed to compile.

./core/components/Noun/words.ts:1:21
Type error: Cannot find module '../../content.yaml' or its corresponding type declarations.

>  1 | import content from "../../content.yaml";
     |                     ^
   3 |
   4 | const words = (content as {
   5 |     words: string[],
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
``` 

# My files

## `package.json`
<details>

```json5
{
    /* ... */
    "scripts": {
        "dev": "next dev",
        "build": "next build",
        "start": "next start"
    },
    "dependencies": {
        "js-yaml-loader": "^1.2.2",
        "mobx": "^6.1.7",
        "next": "10.0.6",
        "node": "^15.8.0",
        "react": "17.0.1",
        "react-dom": "17.0.1",
        "react-router-dom": "5.2.0",
        "styled-components": "5.2.1"
    },
    "devDependencies": {
        "@types/js-yaml": "^4.0.0",
        "@types/node": "^14.14.31",
        "@types/react": "17.0.1",
        "@types/styled-components": "^5.1.7",
        "typescript": "4.1.5"
    }
}
```
</details>

## `webpack.config.js`
<details>

```js
module: {
    rules: [{
        test: /\.ya?ml$/,
        use: 'js-yaml-loader',
    }]
}
```

</details>

## `next.config.js`
<details>

```js
module.exports = {
    webpack: function (config) {
        config.module.rules.push(
            {
                test: /\.ya?ml$/,
                use: 'js-yaml-loader',
            },
        )
        return config
    }
}
```

</details>

## `next-env.d.ts`
<details>

```ts
/// <reference types="next" />
/// <reference types="next/types/global" />
```

</details>

**Comment by luisfelipesdn12** [comment]
Hey guys! I've founded the solution for the issue!

The `js-yaml-loader` makes possible to load the yaml file with `import` statement, however, the ts (who does not recognize it) keep throwing the error. This error block next to build the project, even it being possible, so everything we must do is to say the builder to ignore this ts-error by adding a comment `// @ts-ignore` .

So the final result would be:

```ts
// @ts-ignore
import content from "../../content.yaml";
```

And everything works fine :)

**Comment by wwilsman** [comment]
Thanks for the detailed issue @luisfelipesdn12! Glad you've gotten it figured out too!

I don't personally use TypeScript, but I wonder if you could also work around this by declaring a custom module type for your yaml file? This might also have the benefit of allowing your yaml content to be strongly typed.

```typescript
declare module '../../content.yaml' { 
  export interface MyYaml {
    someProperty: string;
  }
  const content: MyYaml;
  export default content;
}
```

**Comment by luisfelipesdn12** [comment]
> Thanks for the detailed issue @luisfelipesdn12! Glad you've gotten it figured out too!
> 
> I don't personally use TypeScript, but I wonder if you could also work around this by declaring a custom module type for your yaml file? This might also have the benefit of allowing your yaml content to be strongly typed.
> 
> ```typescript
> declare module '../../content.yaml' { 
>   export interface MyYaml {
>     someProperty: string;
>   }
>   const content: MyYaml;
>   export default content;
> }
> ```

Interesting! I'm pretty sure it would work as well :)
