### ISSUE TITLE
Error thrown without passing "options" to the loader

### ISSUE THREAD

**Issue by sjuvonen** [wwilsman/js-yaml-loader#4]
Version 1.0.0 throws an error when trying to configure the loader without explicitly defining `options` with Webpack.

Fails with error "Cannot read property 'safe' of null".

Failing configuration:
```
rules: [
  {
    test: /\.yaml$/,
    use: 'js-yaml-loader'
  }
]
```

Working configuration:
```
rules: [
  {
    test: /\.yaml$/,
    use: [{
      loader: 'js-yaml-loader',
      options: {}
    }]
  }
]
```

**Comment by wwilsman** [comment]
That's a bummer. I'll make a PR and release 1.0.1 for you ASAP!

**Comment by wwilsman** [comment]
Released! That should fix it, but it defaults to `safe` enabled
